<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypeEnginModelsSeeder extends Seeder
{
    public function run(): void
    {
        $models = [
            // Camion benne
            [
                'type_engin_slug' => 'camion-benne',
                'title' => '6 roues (8m3)',
                'subtitle' => '3.5 - 7.5 T',
                'group_tag' => 'Benne',
                'slug' => '6-roues-8m3',
                'serie' => 'A12',
                'carrosserie' => 'Vitre',
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 25000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 20000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 1500,
                'slice_2_max_distance' => 20.0,
                'slice_2_pricing' => 1000,
                'slice_3_pricing' => 500,
                'manutention_pricing' => 5000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 15:45:21',
                'updated_at' => '2025-08-05 15:45:21',
            ],
            [
                'type_engin_slug' => 'camion-benne',
                'title' => '10 roues (12m3)',
                'subtitle' => '10 - 20 T(12m3)',
                'group_tag' => 'Benne',
                'slug' => '10-roues-12m3',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 45000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 45000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 2000,
                'slice_2_max_distance' => 40.0,
                'slice_2_pricing' => 1000,
                'slice_3_pricing' => 500,
                'manutention_pricing' => 10000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 15:47:37',
                'updated_at' => '2025-08-05 15:51:58',
            ],
            [
                'type_engin_slug' => 'camion-benne',
                'title' => '12 roues (20m3)',
                'subtitle' => '20 - 30 T',
                'group_tag' => 'Benne',
                'slug' => '12-roues-20m3',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 90000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 90000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 2500,
                'slice_2_max_distance' => 30.0,
                'slice_2_pricing' => 2000,
                'slice_3_pricing' => 15000,
                'manutention_pricing' => 15000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 15:50:52',
                'updated_at' => '2025-08-05 15:58:27',
            ],

            // Camion plateau standard
            [
                'type_engin_slug' => 'camion-plateau-standard',
                'title' => '4 roues',
                'subtitle' => 'Léger (2 essieux)',
                'group_tag' => 'Plateau',
                'slug' => '4-roues',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 25000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 25000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 1500,
                'slice_2_max_distance' => 10.0,
                'slice_2_pricing' => 1000,
                'slice_3_pricing' => 500,
                'manutention_pricing' => 10000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:00:45',
                'updated_at' => '2025-08-05 16:00:45',
            ],
            [
                'type_engin_slug' => 'camion-plateau-standard',
                'title' => ' 6 roues',
                'subtitle' => 'Moyen (3 essieux)',
                'group_tag' => 'Camion plateau',
                'slug' => '6-roues',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 30000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 30000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 2000,
                'slice_2_max_distance' => 20.0,
                'slice_2_pricing' => 1000,
                'slice_3_pricing' => 500,
                'manutention_pricing' => 15000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:03:07',
                'updated_at' => '2025-08-05 16:03:07',
            ],
            [
                'type_engin_slug' => 'camion-plateau-standard',
                'title' => '8 roues et plus',
                'subtitle' => 'Lourd (4 essieux) ',
                'group_tag' => 'Camion plateau',
                'slug' => '8-roues-et-plus',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 40000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 40000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 5000,
                'slice_2_max_distance' => 10.0,
                'slice_2_pricing' => 2000,
                'slice_3_pricing' => 1000,
                'manutention_pricing' => 20000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:05:00',
                'updated_at' => '2025-08-05 16:05:00',
            ],

            // Camion plateau à ridelles
            [
                'type_engin_slug' => 'camion-plateau-a-ridelles',
                'title' => '4 roues - 2 essieux',
                'subtitle' => 'Léger (2 essieux) : < 7.5 T',
                'group_tag' => 'Camion plateau',
                'slug' => '4-roues-2-essieux',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 20000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 20000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 1500,
                'slice_2_max_distance' => 10.0,
                'slice_2_pricing' => 1000,
                'slice_3_pricing' => 500,
                'manutention_pricing' => 8000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:07:59',
                'updated_at' => '2025-08-05 16:07:59',
            ],
            [
                'type_engin_slug' => 'camion-plateau-a-ridelles',
                'title' => '6 roues - 3 essieux',
                'subtitle' => 'Moyen : 7.5 - 18 T',
                'group_tag' => 'Camion plateau',
                'slug' => '6-roues-3-essieux',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 30000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 30000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 3000,
                'slice_2_max_distance' => 10.0,
                'slice_2_pricing' => 2000,
                'slice_3_pricing' => 1000,
                'manutention_pricing' => 15000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:09:44',
                'updated_at' => '2025-08-05 16:09:44',
            ],
            [
                'type_engin_slug' => 'camion-plateau-a-ridelles',
                'title' => '8 roues et plus - 4 essieux',
                'subtitle' => 'Lourd : 18 - 26 T',
                'group_tag' => 'Camion plateau',
                'slug' => '8-roues-et-plus-4-essieux',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 45000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 45000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 5000,
                'slice_2_max_distance' => 10.0,
                'slice_2_pricing' => 3000,
                'slice_3_pricing' => 1000,
                'manutention_pricing' => 20000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:11:44',
                'updated_at' => '2025-08-05 16:11:44',
            ],

            // Porteur
            [
                'type_engin_slug' => 'porteur',
                'title' => '2 Essieux - 4 Roues',
                'subtitle' => 'Inférieur 7.5 T, livraisons urbaines',
                'group_tag' => 'Porteur',
                'slug' => '2-essieux-4-roues',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 20000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 20000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 1500,
                'slice_2_max_distance' => 10.0,
                'slice_2_pricing' => 1000,
                'slice_3_pricing' => 500,
                'manutention_pricing' => 10000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:23:25',
                'updated_at' => '2025-08-05 16:23:25',
            ],
            [
                'type_engin_slug' => 'porteur',
                'title' => '2 Essieux - 6 Roues',
                'subtitle' => '7.5 - 18 T, Distribution régionale',
                'group_tag' => 'Porteur',
                'slug' => '2-essieux-6-roues',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 30000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 30000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 2000,
                'slice_2_max_distance' => 30.0,
                'slice_2_pricing' => 10000,
                'slice_3_pricing' => 500,
                'manutention_pricing' => 20000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:27:16',
                'updated_at' => '2025-08-05 16:27:16',
            ],
            [
                'type_engin_slug' => 'porteur',
                'title' => '3 Essieux - 6 Roues',
                'subtitle' => '18 - 26 T, Charges plus lourdes',
                'group_tag' => 'Porteur',
                'slug' => '3-essieux-6-roues',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 50000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 50000,
                'slice_1_max_distance' => 5.0,
                'slice_1_pricing' => 5000,
                'slice_2_max_distance' => 40.0,
                'slice_2_pricing' => 3000,
                'slice_3_pricing' => 2000,
                'manutention_pricing' => 25000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:28:59',
                'updated_at' => '2025-08-05 16:28:59',
            ],
            [
                'type_engin_slug' => 'porteur',
                'title' => '4 Essieux - 8 Roues',
                'subtitle' => '18 - 30 T, longues distances',
                'group_tag' => 'Porteur',
                'slug' => '4-essieux-8-roues',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 70000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 70000,
                'slice_1_max_distance' => 10.0,
                'slice_1_pricing' => 10000,
                'slice_2_max_distance' => 40.0,
                'slice_2_pricing' => 5000,
                'slice_3_pricing' => 3000,
                'manutention_pricing' => null,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-05 16:31:09',
                'updated_at' => '2025-08-05 16:31:09',
            ],

            // Bâché
            [
                'type_engin_slug' => 'bache',
                'title' => 'Bâché Moyen ',
                'subtitle' => '(2T)',
                'group_tag' => 'bache',
                'slug' => 'bache',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 10000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 10000,
                'slice_1_max_distance' => 10.0,
                'slice_1_pricing' => 1500,
                'slice_2_max_distance' => 25.0,
                'slice_2_pricing' => 1000,
                'slice_3_pricing' => 800,
                'manutention_pricing' => 10000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-13 11:18:56',
                'updated_at' => '2026-01-12 16:07:08',
            ],
            [
                'type_engin_slug' => 'bache',
                'title' => 'Bâché Grand',
                'subtitle' => '(5T)',
                'group_tag' => 'bache',
                'slug' => 'bache-grand',
                'serie' => null,
                'carrosserie' => null,
                'nombre_essieux' => null,
                'nombre_roues' => null,
                'oil' => null,
                'ability_tonne' => null,
                'ptac_tonne' => null,
                'poids_vide' => null,
                'charge_utile' => null,
                'puissance_fiscale' => null,
                'cylindree' => null,
                'price' => 15000.0,
                'currency_code' => 'XOF',
                'ride_base_pricing' => 15000,
                'slice_1_max_distance' => 15.0,
                'slice_1_pricing' => 2000,
                'slice_2_max_distance' => 30.0,
                'slice_2_pricing' => 1200,
                'slice_3_pricing' => 850,
                'manutention_pricing' => 10000,
                'day_location_price' => null,
                'transport_required_vehicule' => false,
                'transport_km_price' => null,
                'transport_km_price_with_vehicule' => null,
                'created_at' => '2025-08-13 11:26:55',
                'updated_at' => '2025-08-13 11:26:55',
            ],
        ];

        foreach ($models as $model) {
            DB::table('type_engin_models')->updateOrInsert(
                ['slug' => $model['slug']],
                $model
            );
        }
    }
}
